device: "cuda"  # Use "cuda" for GPU, "mps" for Mac, or "cpu"
image_directory: "../data/ResizedImages"
save_image: True
output_dir: "../output"
output_filename: "crop_rows_stitched_small.png"
batch_size: 2
max_workers: 1
left_crop: 29
right_crop: 29
top_crop: 5
bottom_crop: 5
fixed_height: 384
fixed_width: 512
extractor: 'superpoint'
H_transform_method: 'RANSAC' # 'LMEDS'
