device: "cuda"  # Use "cuda" for GPU, "mps" for Mac, or "cpu"
image_directory: "../data/ResizedImages"
mask_image_directory: "../data/Masks"
heatmap_image_directory: "../data/Heatmaps"
save_image: True
output_dir: "../output"
output_filename: "output"
batch_size: 2
max_workers: 1
left_crop: 29
right_crop: 29
top_crop: 5
bottom_crop: 5
fixed_height: 384
fixed_width: 512
extractor: 'superpoint'
H_transform_method: 'RANSAC' # 'LMEDS'
